""" QUERY FOR DELETE """
DROP_ABX_INVOICE = '''DROP TABLE IF EXISTS ABX_INVOICE'''
DROP_ABX_HANDLING = '''DROP TABLE IF EXISTS ABX_HANDLING'''
DROP_AVX_VCL = '''DROP TABLE IF EXISTS AVX_VCL'''
DROP_ATM_TML = '''DROP TABLE IF EXISTS ATM_TML'''
DROP_MCOD_MST = '''DROP TABLE IF EXISTS MCOD_MST'''
DROP_CIN_DIST = '''DROP TABLE IF EXISTS CIN_DIST'''


CREATE_ABX_INVOICE = '''
  create table ABX_INVOICE(
  INVNUM  VARCHAR(20) ,
  CGOTYP  VARCHAR(5),
  ORGADR  TEXT,
  ORGCOD  VARCHAR(10),
  DSTADR  TEXT,
  DSTCOD  VARCHAR(10),
  SNDNAM  TEXT,
  RVCNAM  TEXT,
  CRTDAT  TIMESTAMP,
  PRIMARY KEY(INVNUM))'''
INDEX_ABX_INVOICE = [
  '''CREATE INDEX ORG ON ABX_INVOICE (ORGCOD)''',
  '''CREATE INDEX DST ON ABX_INVOICE (DSTCOD)''',
  '''CREATE INDEX ODP ON ABX_INVOICE (ORGCOD,DSTCOD)'''
  ]

CREATE_ABX_HANDLING = '''
  create table ABX_HANDLING  (
  INVNUM  VARCHAR(20),
  HNDLRCOD  VARCHAR(20),
  HNDLPNT VARCHAR(10),
  HNDLJOBCOD  VARCHAR(1),
  FRM_TO  VARCHAR(10),
  CRTDAT  TIMESTAMP,
  PRIMARY KEY(INVNUM,HNDLRCOD,HNDLPNT,HNDLJOBCOD))'''
INDEX_ABX_HANDLING = [
  '''CREATE INDEX INVNUM ON ABX_HANDLING (INVNUM)''',
  '''CREATE INDEX HNDLRCOD ON ABX_HANDLING (HNDLRCOD)''',
  '''CREATE INDEX HNDLPNT ON ABX_HANDLING (HNDLPNT)''',
  '''CREATE INDEX HNDLJOBCOD ON ABX_HANDLING (HNDLJOBCOD)''',
  '''CREATE INDEX FRM_TO ON ABX_HANDLING (FRM_TO)'''
  ]

CREATE_AVX_VCL = '''
  create table AVX_VCL (
  VCLCOD  VARCHAR(10),
  VCLORG  TEXT,
  VCLTYP  VARCHAR(30),
  VCLOPS  VARCHAR(30),
  VCLCAP_BX INTEGER,
  VCLCAP_RT INTEGER,
  CSTTYP  VARCHAR(1),
  CSTBAS  NUMERIC(20,3),
  CSTBASUNT VARCHAR(1),
  CSTBASLMT NUMERIC(20,3),
  CSTVAR  NUMERIC(20,3),
  CSTVARUNIT  VARCHAR(1),
  CSTVARLMT NUMERIC(20,3),
  PRIMARY KEY(VCLCOD))'''
INDEX_AVX_VCL = [
  '''CREATE INDEX VCLORG ON AVX_VCL (VCLCOD,VCLORG)''',
  ]

CREATE_ATM_TML = '''
  create table ATM_TML(
  TMLCOD  VARCHAR(10),
  TMLASN  VARCHAR(10),
  TMLLOC  TEXT,
  TMLTYP  VARCHAR(5),
  TMLFNC  VARCHAR(1),
  TMLCAPA_BX  INTEGER,
  TMLCAPA_RT  INTEGER,
  TMLOPEN TEXT,
  TMLCLOSE  TEXT,
  HDLCSTTYP VARCHAR(4),
  HDLCSTBSE NUMERIC(20,3),
  HDLCSTBSEUNIT VARCHAR(1),
  HDLCSTVAR NUMERIC(20,3),
  HDLCSTVARUNIT VARCHAR(1),
  HDLCSTVARLMT  NUMERIC(20,3),
  LATITUDE  NUMERIC(20,10),
  LONGITUDE  NUMERIC(20,10),
  PRIMARY KEY(TMLCOD))'''
INDEX_ATM_TML = [
  '''CREATE INDEX TMLASN ON ATM_TML (TMLASN)'''
  ]

CREATE_MCOD_MST = '''
  create table MCOD_MST (
  TBL VARCHAR(30),
  CLM VARCHAR(30),
  COD VARCHAR(10),
  VAL VARCHAR(10),
  DESCRIPTION  TEXT,
  PRIMARY KEY(TBL, CLM, COD))'''


CREATE_CIN_DIST = '''
  create table CIN_DIST(
  TMLFRM  VARCHAR(10),
  TMLTTO  VARCHAR(10),
  DISTANCE  INTEGER,
  UNIT  VARCHAR(5),
  PRIMARY KEY(TMLFRM, TMLTTO))'''
INDEX_CIN_DIST = [
  '''CREATE INDEX FRM ON CIN_DIST (TMLFRM)''',
  '''CREATE INDEX TTO ON CIN_DIST (TMLTTO)'''
  ]



DROPS = [DROP_ABX_INVOICE,DROP_ABX_HANDLING,DROP_AVX_VCL,DROP_ATM_TML,DROP_MCOD_MST,DROP_CIN_DIST]
CREAT = [CREATE_ABX_INVOICE,CREATE_ABX_HANDLING,CREATE_AVX_VCL,CREATE_ATM_TML,CREATE_MCOD_MST,CREATE_CIN_DIST]
INDEX = INDEX_ABX_INVOICE + INDEX_ABX_HANDLING + INDEX_AVX_VCL + INDEX_ATM_TML + INDEX_CIN_DIST